format = """
╭\
[─](bg:#E9F5E5)\
[─](bg:#D1EAC7)\
[─](bg:#B3DCA1)\
$directory\
[ ](bg:#B3DCA1)\
[ ](bg:#D1EAC7)\
[ ](bg:#E9F5E5)\
\n╰─$character """

[directory]
style = "fg:#505050 bg:#A4D58F"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Code" = "󰨞 "
