format = """
[](fg:#A4D58F)\
$directory\
[](fg:#A4D58F)\
\n $character"""

[directory]
style = "fg:#505050 bg:#A4D58F"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Code" = "󰨞 "
