format = """
$directory\
[ ](bg:#F4EDD7)\
[ ](bg:#F4EDD7)\
[ ](bg:#F9F1E7)\
[ ](bg:#F9F1E7)\

\n$character"""

[directory]
style = "fg:#505050 bg:#E2DE90"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Code" = "󰨞 "
