format = """
[░▒▓](#a3aed2)\
[ 󰣇 ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#a3aed2)\
$git_branch\
[](fg:#a3aed2 bg:#a3aed2)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#a3aed2 bg:#a3aed2)\
[ ](fg:#a3aed2)\
\n$character"""

[directory]
style = "fg:#333333 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#333333 bg:#a3aed2)]($style)'


[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#333333 bg:#a3aed2)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#333333 bg:#a3aed2)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#333333 bg:#a3aed2)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#333333 bg:#a3aed2)]($style)'
