general {
    disable_loading_bar = true
    hide_cursor = true
    ignore_empty_input = true    
}

background {
	path = /home/chrysanthemum/Pictures/Wallpapers/green_girl.jpg
	#path = /home/chrysanthemum/Pictures/Wallpapers/zuchold-archtecture.jpg
}

animation {
	bezier = linear, 1, 1, 0, 0
	animation = fade, 1, 5, linear
	animation = inputField, 0
}

auth {
	fingerprint:enabled = false
	fingerprint:ready_message = Touch ID or Enter Password
	fingerprint:present_message = Scanning...
	fingerprint:retry_delay = 0
}

input-field {
    size = 300, 40
    outline_thickness = 1
    rounding = -1
    
    outer_color = rgb(FFFFFF)
    inner_color = rgb(dce0e2)
    font_color = rgb(FFFFFF)
    check_color = rgb(D9534F)
    fail_color = rgb(FFFFFF)

    fade_on_empty = false
    font_family = SF Pro Bold
    placeholder_text = 
    dots_rounding = -1
    dots_center = true
    dots_size = 0.3
    valign = bottom
    halign = center

    fail_text = 
    position = 0, 16%
    shadow_size = 3
    shadow_passes = 3
    swap_font_color = true
    shadow_boost = 0.1
    zindex = 2
}

label {
    text = $FPRINTPROMPT
    color = rgb(e8e8e8)
    font_size = 16
    font_family = SF Pro Bold
    position = 0, 16.5%
    halign = center
    valign = bottom               

    shadow_passes = 3
    shadow_size = 3
	shadow_boost = 0.2
}

label {
    text = $TIME
    color = rgb(e8e8e8)
    font_size = 144
    font_family = SF Pro Bold
	position = 0, -12%
    halign = center
    valign = top               

    shadow_passes = 3
    shadow_size = 3
	shadow_boost = 0.2
}
label {
    text = cmd[update:0:1] echo "$(date +"%A, %B %-d")"
    color = rgb(e8e8e8)
    font_size = 32
    font_family = SF Pro Bold
	position = 0, -10%
    halign = center
    valign = top               

    shadow_passes = 3
    shadow_size = 3
	shadow_boost = 0.2
}


