general {
    disable_loading_bar = true
    hide_cursor = true
    ignore_empty_input = true    
    enable_fingerprint = true
    fingerprint_ready_message =   Scan to unlock
    fingerprint_present_message =   Scanning...
}

background {
   	path = /home/chrysanthemum/Assets/Pictures/Wallpapers/猫.png
	#path = screenshot
   	blur_passes = 0
   	blur_size = 6
   	brightness = 1.2
   	contrast = 0.4
   	noise = 0.025
   	vibrancy = -0.5
}


input-field {
    size = 300, 40
    outline_thickness = 0
    rounding = 3
    
    outer_color = rgb(FFFFFF)
    inner_color = rgba(FFFFFF80)
    font_color = rgb(000000)
    check_color = rgb(D9534F)
    fail_color = rgb(FFFFFF)

    fade_on_empty = true
    placeholder_text = 
    dots_rounding = 1
    dots_center = true
    valign = bottom
    halign = left

    fail_text = 
    position = 70, 40
    shadow_passes = 0
    swap_font_color = true
}

label {
    text = <b>$TIME</b>
    color = rgb(303030)
    font_size = 120
    font_family = DSEG14 Classic
	position = 40, 140
    halign = left
    valign = bottom               

    shadow_passes = 0
}
label {
    text = $FPRINTMESSAGE
    color = rgb(808080)
    font_size = 16
    font_family = Fira Code Nerd Font
	position = 70, 90
    halign = left
    valign = bottom               

    shadow_passes = 0
}

label {
    text = <b>88:88</b>
    color = rgba(0, 0, 0,0.15)
    font_size = 120
    font_family = DSEG14 Classic
	position = 40, 140
    halign = left
    valign = bottom               

    shadow_passes = 0
}


