general {
    before_sleep_cmd = playerctl pause
}

listener {
    timeout = 485                           # in seconds
    on-timeout = notify-send "Sleeping soon..." "To prevent sleep, create any input event" && playerctl pause
}

listener {
    timeout = 500                            # in seconds
    on-timeout = systemctl suspend # command to run when timeout has passed
}
