#preload = ~/Assets/Pictures/Wallpapers/white_clouds_girl.png
#preload = ~/Assets/Pictures/Wallpapers/look_up.png
#preload = ~/Assets/Pictures/Wallpapers/狗狗.png
#preload = ~/Assets/Pictures/Wallpapers/AnimeSwordGirl.png
#preload = ~/Assets/Pictures/Wallpapers/古味道.jpg
preload = ~/Assets/Pictures/Wallpapers/猫.png
preload = ~/Assets/Pictures/Wallpapers/hill.png


wallpaper = , ~/Assets/Pictures/Wallpapers/猫.png



splash = off
