#preload = ~/Assets/Pictures/Wallpapers/white_clouds_girl.png
#preload = ~/Assets/Pictures/Wallpapers/look_up.png
#preload = ~/Assets/Pictures/Wallpapers/狗狗.png
#preload = ~/Assets/Pictures/Wallpapers/AnimeSwordGirl.png
#preload = ~/Assets/Pictures/Wallpapers/古味道.jpg
preload = ~/Assets/Pictures/Wallpapers/greenbus.jpg

wallpaper = , ~/Assets/Pictures/Wallpapers/greenbus.jpg



splash = off
