general {
    disable_loading_bar = true
    hide_cursor = true
    ignore_empty_input = true    
    enable_fingerprint = true
    fingerprint_ready_message =   SCAN TO UNLOCK
    fingerprint_present_message =   SCANNING...
}

background {
   	path = /home/chrysanthemum/Assets/Pictures/Wallpapers/flowers.jpg
	#path = screenshot
   	blur_passes = 2
   	blur_size = 6
   	brightness = 1.2
   	contrast = 0.4
   	noise = 0.025
   	vibrancy = -0.5
}


input-field {
    size = 300, 40
    outline_thickness = 0
    rounding = 3
    
    outer_color = rgb(A0A0A0)
    inner_color = rgba(FFFFFF80)
    font_color = rgb(606060)
    check_color = rgb(D9534F)
    fail_color = rgb(FFFFFF)

    fade_on_empty = true
    placeholder_text = 
    dots_rounding = 1
    dots_center = true
    valign = center
    halign = left

    fail_text = 
    position = 130, -120
    shadow_passes = 0
    swap_font_color = true
}

label {
    text = <b>$TIME</b>
    color = rgb(255, 255, 255)
    font_size = 120
#    font_family = SF Pro Display
    font_family = DSEG14 Classic
	position = 100, 40
    halign = left
    valign = center               

    shadow_passes = 0
}
label {
    text = $FPRINTMESSAGE
    color = rgb(255, 255, 255)
    font_size = 16
    font_family = Fira Code Nerd Font
	position = 130, -72
    halign = left
    valign = center               

    shadow_passes = 0
}

label {
    text = <b>88:88</b>
    color = rgba(255, 255, 255,0.15)
    font_size = 120
    font_family = DSEG14 Classic
	position = 100, 40
    halign = left
    valign = center               

    shadow_passes = 0
}


