monitor = , 1920x1080, auto, 1
monitorv2 {
  output = eDP-1
  mode = 2256x1504@60
  position = 0x0
  scale = 1
  bitdepth = 10
  cm = wide
}
monitor = desc:Dell Inc. DELL U2711 D971T23614WL, 2560x1440@60,-2560x0,1,bitdepth,10,cm,adobe
monitor = eDP-1, disable
