#bind = SUPER, tab, hyprtasking:toggle, all
#bind = SUPER, space, hyprtasking:toggle, cursor

plugin {
	hyprtasking {
        rows = 3
        exit_behavior = hovered
        gap_size = 8
        bg_color = rgb(000000)
    }

	overview {
		workspaceActiveBackground = rgb(EEEEEE)
		workspaceInactiveBorder = 	rgb(FFFFFF)
		workspaceActiveBorder = 	rgb(A0A0A0)
		panelColor = 				rgb(FAFAFA)
		panelBorderColor = 			rgb(A0A0A0)
		exitOnClick =  1
		overrideGaps =  1
		dragAlpha = 0.9
		panelHeight =   180
		panelBorderWidth = 3
		onBottom = 0
		affectStrut = 1
		disableBlur = 1
		disableGestures =  1
		showEmptyWorkspace = 0
		drawActiveWorkspace = 0
		showSpecialWorkspace = 0
		workspaceBorderSize = 1
		reverseSwipe = 0
	}	
}
