# Window Rules
windowrule = float, class:^(xdg-desktop-portal-gtk|io.bassi.Amberol|python3|org.gnome.Loupe|com.github.huluti.Curtail|dev.bragefuglseth.Fretboard|eww|com.github.GradienceTeam.Gradience|pavucontrol|blueman-manager|nm-connection-editor|blueberry.py|Color Picker|Network|xdg-desktop-portal|xdg-desktop-portal-hyprland|xdg-desktop-portal-gnome|io.github.nate_xyz.Chromatic|it.mijorus.whisper|io.github.giantpinkrobots.flatsweep|VirtualBox Machine|org.gnome.Nautilus|floatterm|moe.launcher.an-anime-game-launcher|org.gnome.clocks|org.gnome.Calculator|io.github.kaii_lb.Overskride|org.matplotlib.Matplotlib3|org.gnome.Decibels|org.kde.dolphin|org.kde.gwenviewsudo|io.github.nokse22.trivia-quiz|com.saivert.pwvucontrol|io.missioncenter.MissionCenter|com.jeffser.Alpaca|org.kde.plasmashell|pavucontrol-qt|hu.irl.cameractrls|org.freedesktop.impl.portal.desktop.kde|mpv)$
windowrule = suppressevent maximize, class:.*$ 
windowrule = size 55% 50%, class:^(org.gnome.Nautilus|org.kde.dolphin)

windowrule = center, class:^(org.gnome.Nautilus|org.kde.dolphin)

windowrule = stayfocused, title:^(Save Image|New Layer|Rotate View|polkit-gnome-authentication-agent-1)$


windowrule = float, title:Picture-in-Picture$
windowrule = size 30% 30%, title:Picture-in-Picture$
windowrule = move 69.3% 69%, title:Picture-in-Picture$
windowrule = pin, title:Picture-in-Picture$

windowrule = noanim, class:wleave
windowrule = float, class:wleave

# Layer Rules
layerrule = noanim, selection$
layerrule = noanim, hyprpicker$
layerrule = animation popin, ch.wysbd.hyprland-preview-screen-picker$

# Touchpad Speeds
windowrule = scrolltouchpad 0.3, class:^(dev.zed.Zed|org.gnome.Papers|com.github.flxzt.rnote)$
windowrule = scrolltouchpad 0.5, class:^(foot|floatterm)$



# Workspace Rules
windowrule = workspace special:discord, class:vesktop
windowrule = workspace special:spotify, class:Spotify
windowrule = workspace special:code, class:dev.zed.Zed
windowrule = workspace special:kden, class:^(org.kde.kdenlive|org.freecad.FreeCAD|org.shotcut.Shotcut)$
windowrule = workspace special:game, class:^(genshinimpact.exe|osu!|moe.launcher.an-anime-game-launcher)$
windowrule = workspace special:game, title:(Minecraft)(.*)$
windowrule = workspace special:windows, class:virt-viewer
windowrule = workspace special:obs, class:com.obsproject.Studio
windowrule = workspace special:note, class:SiYuan

windowrule = fullscreen, class:^(osu!|dev.zed.Zed|SiYuan|virt-viewer)$

workspace=special:code,		on-created-empty:	zeditor

workspace=special:discord, 	on-created-empty: 	vesktop --enable-ozone-platform=wayland  --enable-wayland-ime
workspace=special:spotify, 	on-created-empty: 	spotify-launcher --skip-update
#workspace=special:kden, 	on-created-empty: 	kdenlive
workspace=special:obs,	 	on-created-empty: 	obs
workspace=special:note,		on-created-empty:	siyuan-note --enable-ozone-platform=wayland  --enable-wayland-ime
workspace=special:windows, on-created-empty: virt-viewer --connect qemu:///system --attach win11
