# Window Rules
windowrule = float, ^(xdg-desktop-portal-gtk|io.bassi.Amberol|python3|org.gnome.Loupe|com.github.huluti.Curtail|dev.bragefuglseth.Fretboard|eww|com.github.GradienceTeam.Gradience|pavucontrol|blueman-manager|nm-connection-editor|blueberry.py|Color Picker|Network|xdg-desktop-portal|xdg-desktop-portal-hyprland|xdg-desktop-portal-gnome|io.github.nate_xyz.Chromatic|it.mijorus.whisper|io.github.giantpinkrobots.flatsweep|VirtualBox Machine|org.gnome.Nautilus|floatterm|moe.launcher.an-anime-game-launcher|org.gnome.clocks|org.gnome.Calculator|io.github.kaii_lb.Overskride|org.matplotlib.Matplotlib3|org.gnome.Decibels|org.kde.dolphin|org.kde.gwenviewsudo|io.github.nokse22.trivia-quiz|com.saivert.pwvucontrol|io.missioncenter.MissionCenter|com.jeffser.Alpaca|org.kde.plasmashell)$
windowrule = suppressevent maximize, ^(.*)$ 
windowrule = size 55% 50%, ^(org.gnome.Nautilus|org.kde.dolphin)

windowrule = center, ^(org.gnome.Nautilus|org.kde.dolphin)

windowrule = stayfocused, title:^(Save Image|New Layer|Rotate View|polkit-gnome-authentication-agent-1)$


windowrulev2 = float, title:Picture-in-Picture$
windowrulev2 = size 30% 30%, title:Picture-in-Picture$
windowrulev2 = move 69.3% 69%, title:Picture-in-Picture$
windowrulev2 = pin, title:Picture-in-Picture$

windowrule = noanim, wleave
windowrule = float, wleave

# Layer Rules
layerrule = noanim, selection$
layerrule = noanim, hyprpicker$

# Touchpad Speeds
windowrule = scrolltouchpad 0.3, ^(dev.zed.Zed)$
windowrule = scrolltouchpad 0.5, ^(foot|floatterm)$



# Workspace Rules
windowrule = workspace special:discord, vesktop
windowrule = workspace special:spotify, Spotify
windowrule = workspace special:code, dev.zed.Zed
windowrule = workspace special:kden, ^(org.kde.kdenlive|org.freecad.FreeCAD)$
windowrule = workspace special:game, ^(genshinimpact.exe|osu!|moe.launcher.an-anime-game-launcher)$
windowrule = workspace special:game, title:(Minecraft)(.*)$
windowrule = workspace special:obs, com.obsproject.Studio
windowrule = workspace special:note, SiYuan

windowrule = fullscreen, ^(spotify|vesktop|osu!|dev.zed.Zed|SiYuan)$
windowrule = immediate, ^(spotify|vesktop|osu!)$

workspace=special:windows, 	on-created-empty:	waydroid show-full-ui
workspace=special:code,		on-created-empty:	zeditor

workspace=special:discord, 	on-created-empty: 	vesktop --enable-ozone-platform=wayland  --enable-wayland-ime
workspace=special:spotify, 	on-created-empty: 	spotify-launcher --skip-update
#workspace=special:kden, 	on-created-empty: 	kdenlive
workspace=special:obs,	 	on-created-empty: 	obs
workspace=special:note,		on-created-empty:	siyuan-note --enable-ozone-platform=wayland  --enable-wayland-ime
