general {
    gaps_in = 8
    gaps_out = 16
    gaps_workspaces = 0

    border_size = 2
    col.active_border = rgb(A0A0A0)
    col.inactive_border = rgb(C0C0C0)
    
    layout = dwindle
}
dwindle {
	#special_scale_factor = 0.9
	pseudotile = true
	single_window_aspect_ratio = 4 3
}
input {  
  touchpad {
  	scroll_factor = 0.2
  	clickfinger_behavior = true
  	disable_while_typing = false
  	tap-and-drag = true
    natural_scroll = true
	drag_lock = 0
  }
  sensitivity = 0.4
  accel_profile = flat
  repeat_rate = 50
  force_no_accel = true
  repeat_delay = 200

	# Focus Stuff
  follow_mouse =  2
}

cursor {
	enable_hyprcursor = false
	inactive_timeout = 0
}
gestures {
  #workspace_swipe_distance = 800
  #workspace_swipe_min_speed_to_force = 40
  workspace_swipe_cancel_ratio = 0.1
  #workspace_swipe_min_fingers = 3 
  workspace_swipe_direction_lock = false
}

dwindle {
  pseudotile = true
  preserve_split = true
}

binds {
	scroll_event_delay = 0
	hide_special_on_workspace_change = true
}

misc {	
	disable_autoreload = true
	allow_session_lock_restore = true
	new_window_takes_over_fullscreen = 2
	focus_on_activate = true
	animate_manual_resizes = false
	vrr = 1
	vfr = true
	initial_workspace_tracking = 0
	middle_click_paste = false
}

ecosystem {
	no_update_news = true
	no_donation_nag = true
}

xwayland {
	enabled = true
	force_zero_scaling = true
	use_nearest_neighbor = true
}

decoration {
  rounding = 8

  shadow {
  	enabled = true
  	range = 24
  	render_power = 3
  	color = rgba(00000020)
  	color_inactive = rgba(00000060)
  	
  }
  dim_inactive = false
  dim_strength = 0
  dim_special = 0.5


  #screen_shader = ~/Code/Config/hypr/Shaders/vibrance.glsl
  #screen_shader = ~/Code/Config/hypr/Shaders/night.glsl
  #screen_shader = ~/Code/Config/hypr/Shaders/invert.frag
  #screen_shader = ~/Code/Config/hypr/Shaders/drugs.frag
  #screen_shader = ~/Code/Config/hypr/Shaders/chromatic_abberation.frag
  #screen_shader = ~/Code/Config/hypr/Shaders/solarized.frag
  #screen_shader = ~/Code/Config/hypr/Shaders/crt.frag
  #screen_shader = ~/Code/Config/hypr/Shaders/grayscale.glsl
  
  blur {
    enabled = true
   	special = false
	popups = true
	xray = false
    ignore_opacity = false
    size = 4
    passes = 2
    contrast = 1
    brightness = 0.7
    vibrancy = 0
    noise = 0.05
  }
}
animations {
	enabled = true
}
render {
	new_render_scheduling = true
}
ecosystem {
	no_donation_nag = true
}
