general {
    gaps_in = 12
    gaps_out = 16
    gaps_workspaces = 0

    border_size = 1
    col.active_border = 0xff505050
    col.inactive_border = 0xff444444
    
    resize_on_border = true
}
layout {
	single_window_aspect_ratio = 4 3
}
dwindle {
	#special_scale_factor = 0.9
	pseudotile = true
	preserve_split = true
}
scrolling {
	column_width = 0.4
}
input {  
  touchpad {
  	scroll_factor = 0.2
  	clickfinger_behavior = true
  	disable_while_typing = false
  	tap-and-drag = true
    natural_scroll = true
	drag_lock = 0
  }
  sensitivity = 0.4
  accel_profile = flat
  repeat_rate = 50
  force_no_accel = true
  repeat_delay = 200

	# Focus Stuff
  # follow_mouse =  2
}

cursor {
	enable_hyprcursor = true
	inactive_timeout = 0
	zoom_factor = 1
	use_cpu_buffer = 0
	no_warps = true
}
gestures {
  workspace_swipe_distance = 700
  #workspace_swipe_min_speed_to_force = 40
  workspace_swipe_cancel_ratio = 0.1
  workspace_swipe_direction_lock = false
}

dwindle {
  pseudotile = true
  preserve_split = true
}

binds {
	scroll_event_delay = 0
	hide_special_on_workspace_change = true
}

misc {	
	disable_autoreload = false
	allow_session_lock_restore = true
	focus_on_activate = true
	animate_manual_resizes = false
	vrr = 1
	vfr = true
	initial_workspace_tracking = 0
	middle_click_paste = false
}

ecosystem {
	no_update_news = true
	no_donation_nag = true
}

xwayland {
	enabled = true
	force_zero_scaling = true
	use_nearest_neighbor = true
}

decoration {
  rounding = 8

  shadow {
  	enabled = true
  	range = 24
  	render_power = 4
  	color = rgba(00000040)
  	color_inactive = rgba(00000025)  	
  }
  
  dim_inactive = false
  dim_strength = 0
  dim_special = 0.3
  dim_around = 0.6


  #screen_shader = ~/Code/Config/hypr/Shaders/vibrance.glsl
  #screen_shader = ~/Code/Config/hypr/Shaders/night.glsl
  #screen_shader = ~/Code/Config/hypr/Shaders/invert.frag
  #screen_shader = ~/Code/Config/hypr/Shaders/drugs.frag
  #screen_shader = ~/Code/Config/hypr/Shaders/chromatic_abberation.frag
  #screen_shader = ~/Code/Config/hypr/Shaders/solarized.frag
  #screen_shader = ~/Code/Config/hypr/Shaders/crt.frag
  #screen_shader = ~/Code/Config/hypr/Shaders/grayscale.glsl
  
  blur {
    enabled = true
   	special = false
	popups = false
	input_methods = false
	xray = false
    ignore_opacity = false
    size = 8
    passes = 3
    contrast = 1
    brightness = 1
    vibrancy = 0
    noise = 0.04
  }
}
animations {
	enabled = true
}
render {
	new_render_scheduling = true
}
ecosystem {
	no_donation_nag = true
}
