# -*- conf -*-

# app-id=foot # globally set wayland app-id. Default values are "foot" and "footclient" for desktop and server mode

font=Fira Code Nerd Font:size=12
# font-size-adjustment=0.5
# line-height=<font metrics>
# letter-spacing=0
# horizontal-letter-offset=0
# vertical-letter-offset=0
# underline-offset=<font metrics>
# underline-thickness=<font underline thickness>
# box-drawings-uses-font-glyphs=no
# dpi-aware=no

# initial-window-size-pixels=700x500  # Or,
initial-window-size-chars=96x32
# initial-window-mode=windowed
pad=12x0                           # optionally append 'center'
# resize-delay-ms=100

# notify=notify-send -a ${app-id} -i ${app-id} ${title} ${body}

# bold-text-in-bright=no
# word-delimiters=,│`|:"'()[]{}<>
# selection-target=primary
# workers=<number of logical CPUs>
# utmp-helper=/usr/lib/utempter/utempter  # When utmp backend is ‘libutempter’ (Linux)
# utmp-helper=/usr/libexec/ulog-helper    # When utmp backend is ‘ulog’ (FreeBSD)

[environment]
# name=value

[bell]
# urgent=no
# notify=no
# visual=no
# command=
# command-focused=no

[scrollback]
# lines=1000
multiplier=4.0
# indicator-position=relative
# indicator-format=""

[url]
# launch=xdg-open ${url}
# label-letters=sadfjklewcmpgh
# osc8-underline=url-mode
# protocols=http, https, ftp, ftps, file, gemini, gopher
# uri-characters=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_.,~:;/?#@!$&%*+="'()[]

[cursor]
style=beam
# color=<inverse foreground/background>
# blink=no
# beam-thickness=1.5
# underline-thickness=<font underline thickness>

[mouse]
# hide-when-typing=no
# alternate-scroll-mode=yes

[colors]
# alpha=0.9
cursor=11111b f5e0dc

[colors]
foreground=ECEFF1
background=333333
regular0=546E7A  # black
regular1=FF5252  # red
regular2=5CF19E  # green
regular3=FFD740  # yellow
regular4=40C4FF  # blue
regular5=FF4081  # magenta
regular6=64FCDA  # cyan
regular7=FFFFFF  # white
bright0=B0BEC5   # bright black
bright1=FF8A80   # bright red
bright2=B9F6CA   # bright green
bright3=FFE57F   # bright yellow
bright4=80D8FF   # bright blue
bright5=FF80AB   # bright magenta
bright6=A7FDEB   # bright cyan
bright7=FFFFFF   # bright white

16=fab387
17=f5e0dc

selection-foreground=cdd6f4
selection-background=414356

search-box-no-match=11111b f38ba8
search-box-match=cdd6f4 313244

jump-labels=11111b fab387
urls=89b4fa
