[window]
width = 420
height = 940
anchor = "left"
margin_top = 0
margin_bottom = 0
margin_left = 24
margin_right = 0
show_descriptions = false
show_paths = false
show_icons = true
show_search = true
show_actions = false
show_border = true
border_width = 2
use_gtk_colors = false
use_custom_css = false
max_entries = 50

[window.custom_navigate_keys]
up = "k"
down = "j"
delete_word = "h"

[theme.colors]
window_bg = "#0f0f0f30"
search_bg = "#0f0f0f30"
search_bg_focused = "#282828"
item_bg = "#0f0f0f00"
item_bg_hover = "#18181880"
item_bg_selected = "#1f1f1f80"
search_text = "#e0e0e0"
search_caret = "#808080"
item_name = "#ffffff"
item_name_selected = "#ffffff"
item_description = "#a0a0a0"
item_description_selected = "#a0a0a0"
item_path = "#808080"
item_path_selected = "#808080"
border = "#404040"

[theme.corners]
window = 8
search = 6
list_item = 4

[theme.spacing]
search_margin = 0
search_padding = 12
item_margin = 6
item_padding = 4

[theme.typography]
search_font_size = 16
item_name_size = 14
item_description_size = 12
item_path_size = 12
item_path_font_family = "monospace"

[debug]
disable_auto_focus = false
enable_logging = false

[calculator]
enabled = true

[dmenu]
allow_invalid = false
case_sensitive = false

[web_search]
enabled = true
engine = "google"
prefixes = []
